import Navbar from '@/components/Navbar'
import Providers from '@/components/Providers'
import { cn, constructMetadata } from '@/lib/utils'
import { Inter } from 'next/font/google'
import type { Viewport } from 'next'

// Import Tailwind first
import './globals.css'

// Then other styles
import 'react-loading-skeleton/dist/skeleton.css'
import 'simplebar-react/dist/simplebar.min.css'

import { Toaster } from '@/components/ui/toaster'

const inter = Inter({ subsets: ['latin'] })

export const metadata = constructMetadata()

export const viewport: Viewport = {
  themeColor: '#FFF',
}

/*
export const viewport: Viewport = {
  themeColor: '#zinc-700',
}*/

/* put this under html lang="en" in the return statement, if not working
 <head>
        <link rel="stylesheet" href="/globals.css" />
      </head>
*/

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className='light'>
      <head>
        <link rel="stylesheet" href="/globals.css" />
      </head>
      <body
        className={cn(
          'min-h-screen font-sans antialiased grainy flex flex-col',
          inter.className
        )}>
        <Providers>
          <Toaster />
          <Navbar />
          <div className="flex-1 flex flex-col">
            {children}
          </div>
        </Providers>
      </body>
    </html>
  )
}




//Make changes to home page layout here in layout.tsx (such as color of background)
/*

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
*/